### ISSUE TITLE
-webkit-image-set

### ISSUE THREAD

**Issue by yratanov** [srowhani/sass-lint-auto-fix#53]
## Problem Description

I get an error when trying to fix a file that is using `-webkit-image-set` function.

## Screenshot

![error](https://user-images.githubusercontent.com/1536262/46094003-bcc17500-c1b0-11e8-9967-1b6f43a4a9a6.png)

**Comment by srowhani** [comment]
Parse errors occur when the library that I use to read in the s(a|c)ss has issues parsing the file. It seems that this problem lies in gonzales.

If you're running this on a set of files, it won't stop early. I just added this message give context on why the auto resolver won't run on the file you gave it.
